In [10]:
def fold(n,df):
    seed(1)
    index1=cross_validation_split(df[0],5) 
    index1=pd.DataFrame(data=index1)
    index1=index1.T
    S=np.array([0,1,2,3,4]) # Number of folds
    #testing set
    X0_list=list()
    X1_list=list()
    X2_list=list()
    Y_list=list()
    list_df0 = list(df[0])
    list_df1 = list(df[1])
    list_df2 = list(df[2])
    list_y = list(df[3])
    for i in index1[5-n]:
        X0_list.append(list_df0[i])
        X1_list.append(list_df1[i])
        X2_list.append(list_df2[i])
        Y_list.append(list_y[i])
    
    x0_test=np.array(X0_list)
    x1_test=np.array(X1_list)
    x2_test=np.array(X2_list)
    y_test=np.array(Y_list)
   
    S=np.delete(S, 5-n)
    # training set
    X0_list=list()
    X1_list=list()
    X2_list=list()
    Y_list=list()
    list_df0 = list(df[0])
    list_df1 = list(df[1])
    list_df2 = list(df[2])
    list_y = list(df[3])
    for j in S:
        for i in index1[j]:
            X0_list.append(list_df0[i])
            X1_list.append(list_df1[i])
            X2_list.append(list_df2[i])
            Y_list.append(list_y[i])
    x0_train=np.array(X0_list)
    x1_train=np.array(X1_list)
    x2_train=np.array(X2_list)
    y_train=np.array(Y_list )
    
    
    y_train=y_train.reshape(388,1)
    x_train=np.vstack((x0_train,x1_train,x2_train))
    x_test=np.vstack((x0_test,x1_test,x2_test))   
    x_mean = x_train.T.mean(axis=0)
    x_stdev = x_train.T.std(axis=0)
    x_train_norm = (x_train.T - x_mean.T)/(x_stdev.T)
    x_train_norm_aug = np.c_[np.ones((x_train_norm.shape[0], 1)), x_train_norm]

    x_test_norm = (x_test.T - x_mean.T)/(x_stdev.T)
    x_test_norm_aug = np.c_[np.ones((x_test_norm.shape[0], 1)), x_test_norm]
    
    return x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train

In [12]:
def Lin_Reg_Mat_inv(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train):
    print("Linear Regression: Matrix Inversion")
    reg = regression()
    w_pred_mat_inv = reg.mat_inv(y_train,x_train_norm_aug.T)
    print("Parameters")
    print(w_pred_mat_inv)

    Ypred = np.dot(x_train_norm_aug, w_pred_mat_inv)

    train_error = reg.error(w_pred_mat_inv, y_train, x_train_norm_aug.T)/((np.max(y_train)-np.mean(y_train))**2)

    test_error = reg.error(w_pred_mat_inv, y_test, x_test_norm_aug.T)/((np.max(y_test)-np.mean(y_test))**2)

    print('Normalized training error = ', train_error)
    print('Normalized testing error = ', test_error)

In [18]:
# By Gradient Descent Method
def Lin_Reg_Grad_Descent(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train):
    print("Linear Regression: Gradient Descent Method ")
    lr = 0.01
    reg = regression()
    w_pred,err = reg.Regression_grad_des(x_train_norm_aug.T,y_train,lr)
    print("Parameters:")
    print(w_pred)
    train_error = reg.error(w_pred, y_train, x_train_norm_aug.T)/((np.max(y_train)-np.mean(y_train))**2)
    test_error = reg.error(w_pred, y_test, x_test_norm_aug.T)/((np.max(y_test)-np.mean(y_test))**2)

    print('Normalized training error = ', train_error)
    print('Normalized testing error = ', test_error)


In [14]:
print("Linear Regression")
for f in range(1,6):
    print(f," - Fold")
    x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train=fold(f,df)
    Lin_Reg_Mat_inv(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train)
    

Linear Regression
1  - Fold
Linear Regression: Matrix Inversion
Parameters
[[ 4.57675515]
 [ 0.64809252]
 [-0.77313948]
 [-0.36694189]]
Normalized training error =  0.023521636606100592
Normalized testing error =  0.23600446634498648
2  - Fold
Linear Regression: Matrix Inversion
Parameters
[[ 4.61031186]
 [ 0.55917371]
 [-0.82969551]
 [-0.39831487]]
Normalized training error =  0.023815931619799544
Normalized testing error =  0.16939340407906747
3  - Fold
Linear Regression: Matrix Inversion
Parameters
[[ 4.63071649]
 [ 0.55510568]
 [-0.80921835]
 [-0.38249743]]
Normalized training error =  0.025217820095614775
Normalized testing error =  0.16555079307156453
4  - Fold
Linear Regression: Matrix Inversion
Parameters
[[ 4.6095    ]
 [ 0.60173217]
 [-0.79690186]
 [-0.33106879]]
Normalized training error =  0.025962673557047053
Normalized testing error =  0.1815224276826107
5  - Fold
Linear Regression: Matrix Inversion
Parameters
[[ 4.56814948]
 [ 0.58077889]
 [-0.7874266 ]
 [-0.30916919]]
N

In [19]:
print("Linear Regression")
for f in range(1,6):
    print(f," - Fold")
    x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train=fold(f,df)
    Lin_Reg_Grad_Descent(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train)
    

Linear Regression
1  - Fold
Linear Regression: Gradient Descent Method 
Parameters:
[[ 4.57675515]
 [ 0.64816528]
 [-0.77306518]
 [-0.36694464]]
Normalized training error =  0.02352163673804318
Normalized testing error =  0.23600534716132615
2  - Fold
Linear Regression: Gradient Descent Method 
Parameters:
[[ 4.61031185]
 [ 0.5593609 ]
 [-0.82949339]
 [-0.39833699]]
Normalized training error =  0.02381593263980761
Normalized testing error =  0.16938960924135713
3  - Fold
Linear Regression: Gradient Descent Method 
Parameters:
[[ 4.63071649]
 [ 0.55538884]
 [-0.80892082]
 [-0.38251906]]
Normalized training error =  0.025217822293481698
Normalized testing error =  0.165546036183403
4  - Fold
Linear Regression: Gradient Descent Method 
Parameters:
[[ 4.60949999]
 [ 0.60188276]
 [-0.79674205]
 [-0.33108419]]
Normalized training error =  0.02596267420688555
Normalized testing error =  0.18151836901365115
5  - Fold
Linear Regression: Gradient Descent Method 
Parameters:
[[ 4.56814948]
 [ 0.5

In [28]:
def data_transform(X,degree): 
    X_new=np.ones((X.shape[0],1))
    for i in range(1,degree+1): 
        X_new = np.c_[X_new,X**i]
    return X_new.T

def Poly_Mat_inv(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train,deg):
    print("Polynomial Regression-Matrix Inversion")
    reg=regression()
    for degree in range(0,deg+1):
        print("degree: ",degree)
        X_0=data_transform(x_train_norm,degree)
        w_mat = reg.mat_inv(y_train, X_0)
        y_pred=X_0.T @ w_mat
        train_error = reg.error(w_mat, y_train, X_0)/((np.max(y_train)-np.mean(y_train))**2)
        X_0=data_transform(x_test_norm,degree)
        test_error = reg.error(w_mat, y_test, X_0)/((np.max(y_test)-np.mean(y_test))**2)

        print('Normalized training error = ', train_error)
        print('Normalized testing error = ', test_error)
        
# By Gradient Descent Method
def Poly_Grad_Descent(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train,deg):
    print("Polynomial Regression-Gradient Descent")
    reg=regression()
    for degree in range(0,deg+1):
        print("degree: ",degree)
        X_0=data_transform(x_train_norm,degree)
        lr = 0.01
        w_pred,err = reg.Regression_grad_des(X_0,y_train,lr)
        train_error = reg.error(w_pred, y_train, X_0)/((np.max(y_train)-np.mean(y_train))**2)
        X_0=data_transform(x_test_norm,degree)
        test_error = reg.error(w_pred, y_test, X_0)/((np.max(y_test)-np.mean(y_test))**2)

        print('Normalized training error = ', train_error)
        print('Normalized testing error = ', test_error)


In [25]:
print("Polynomial Regression")
for f in range(1,6):
    print(f," - Fold")
    x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train=fold(f,df)
    Poly_Mat_inv(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train,4)
    

Polynomial Regression
1  - Fold
Polynomial Regression-Matrix Inversion
degree:  0
Normalized training error =  0.09167857605784512
Normalized testing error =  0.13523788913257284
degree:  1
Normalized training error =  0.023521636606100592
Normalized testing error =  0.23600446634498648
degree:  2
Normalized training error =  0.015960124846897957
Normalized testing error =  0.24254498727741475
degree:  3
Normalized training error =  0.01580576518892422
Normalized testing error =  0.2411732553235779
degree:  4
Normalized training error =  0.014673412314078616
Normalized testing error =  0.24387502964651955
2  - Fold
Polynomial Regression-Matrix Inversion
degree:  0
Normalized training error =  0.09267182404591212
Normalized testing error =  0.09372812437458397
degree:  1
Normalized training error =  0.023815931619799544
Normalized testing error =  0.16939340407906747
degree:  2
Normalized training error =  0.0159495296391078
Normalized testing error =  0.16725702345461468
degree:  3
Nor

In [30]:
print("Polynomial Regression")
for f in range(1,6):
    print(f," - Fold")
    x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train=fold(f,df)
    Poly_Grad_Descent(x_train,y_train,x_test,y_test,x_train_norm,x_train_norm_aug,x_test_norm,x_test_norm_aug,x0_train,x1_train,x2_train,3)
    

Polynomial Regression
1  - Fold
Polynomial Regression-Gradient Descent
degree:  0
Normalized training error =  0.09167857605784512
Normalized testing error =  0.13523788920331944
degree:  1
Normalized training error =  0.02352164137808925
Normalized testing error =  0.23600978238029985
degree:  2
Normalized training error =  0.01598123353601916
Normalized testing error =  0.24334597557944815
degree:  3
Normalized training error =  0.015884963394764792
Normalized testing error =  0.2417221598679061
2  - Fold
Polynomial Regression-Gradient Descent
degree:  0
Normalized training error =  0.09267182404591212
Normalized testing error =  0.09372812434339489
degree:  1
Normalized training error =  0.0238159320465563
Normalized testing error =  0.16939095809133023
degree:  2
Normalized training error =  0.015964013319621394
Normalized testing error =  0.16723954639433994
degree:  3
Normalized training error =  0.01582012730588988
Normalized testing error =  0.16733747930752468
3  - Fold
Polyno

In [44]:
print("Best Fit for Feature 1-2-3 is found to be polynomial regression of degree 2")
X0=df[0]
X1=df[1]
X3=df[2]
Y=df[3]
x=np.vstack((X0,X1,X3))
x_mean = x.T.mean(axis=0)
x_stdev = x.T.std(axis=0)
x_norm = (x.T - x_mean.T)/(x_stdev.T)
x_norm_aug = np.c_[np.ones((x_norm.shape[0], 1)), x_norm]
reg = regression()
X = data_transform(x_norm,2)
#print("Matrix Inversion")
w_mat = reg.mat_inv(Y, X)
print("Parameters")
print(w_mat)
y_pred=X.T @ w_mat
train_error = reg.error(w_mat, Y, X)/((np.max(Y)-np.mean(Y))**2)
print('Normalized training error = ', train_error)
X = data_transform(x_norm,2)
       

Best Fit for Feature 1-2-3 is found to be polynomial regression of degree 2
Parameters
[ 4.2504794   0.50108123 -0.94310413 -0.3593963   0.22406877  0.11226913
 -0.04439224]
Normalized training error =  0.015600557307775879
